/**
 * The relay between a Feedback Note's Follow-up thread and its GitHub issue
 * (ADR 0019). Everything here is pure: the prompts the server sends, and the
 * one decision that must never depend on a model — which comments are dropped
 * before a model is asked anything at all.
 */

/**
 * The maintainer's triage agent posts its briefs as ordinary comments under the
 * maintainer's own GitHub account, so `comment.user.type === 'Bot'` matches
 * none of them. This marker line, which the agent always writes, is what
 * actually identifies them.
 */
export const TRIAGE_COMMENT_MARKER = 'generated by ai during triage';

/**
 * Whether an issue comment is dropped outright, before laundering. A dropped
 * comment costs the submitter nothing: the Note's outcome message is the
 * guarantee that something always arrives.
 */
export function shouldDropComment(raw: string | null | undefined): boolean {
  const body = (raw || '').trim();
  if (!body) return true;
  return body.toLowerCase().includes(TRIAGE_COMMENT_MARKER);
}

/** Restates one issue comment for the person who filed the Note. */
export const LAUNDER_INSTRUCTION = `You restate a developer's comment from a private issue tracker for the non-technical person who reported the underlying problem in a campus ministry app.
RULES:
1. Write at most two short sentences, in plain warm English, addressed to the reporter.
2. Never mention GitHub, issues, pull requests, branches, commits, tickets, labels, or any "#123" reference. The reporter cannot open any of them.
3. Never include code, file paths, stack traces, error text, log output, or internal shorthand.
4. Never invent a status, a promise, or a date that the comment does not state.
5. If the comment is internal bookkeeping with nothing meaningful for the reporter — a cross-reference, a duplicate note, a build result, a task hand-off — set "relay" to false and leave "text" empty.`;

/**
 * Writes the sentence a submitter reads when their Note ships, from the pull
 * request that closed the issue. ADR 0017 could not do this because nothing
 * linked an issue to a release; a PR is linked to its issue by the close.
 */
export const CLOSE_SUMMARY_INSTRUCTION = `A person using a campus ministry app reported something, and the change that addresses it has now shipped. Tell them what changed, from the pull request that shipped it.
RULES:
1. Write one or two short sentences, plain warm English, addressed to them, present tense ("You can now...", "The ... now ...").
2. Lead with what they can now do or see. Do not describe the implementation.
3. Never mention GitHub, pull requests, issues, commits, branches, files, functions, or any "#123" reference.
4. Never include code, file paths or error text.
5. Say only what the description supports. If it gives you nothing a user would notice, set "usable" to false.
6. Do not thank them or sign off — the app adds its own closing line.`;
