import { describe, it, expect } from 'vitest';
import { shouldDropComment, TRIAGE_COMMENT_MARKER, LAUNDER_INSTRUCTION, CLOSE_SUMMARY_INSTRUCTION } from '../lib/feedbackRelay';

/**
 * The bodies below are verbatim openings of real comments on this repo's own
 * feedback issues. They are the reason the relay launders at all: under a
 * plain `user.type === 'Bot'` filter every one of them is authored by a human
 * OWNER account and would have reached a Community user untouched.
 */
const AGENT_BRIEF_946 =
  '> *This was generated by AI during triage.*\n\n## Agent Brief\n\n**Category:** bug\n**Summary:** Insert Verse toolbar inserts at section start instead of the caret';

const SUPERSEDED_906 =
  '> *This was generated by AI during triage.*\n\nSuperseded by #917, which specifies the toolbar focus/scroll fix in full.';

const HUMAN_SHORTHAND_906 =
  "Specced as Shir0o/cisa-campus-work-tracker#910. Confirmed as the textarea rather than the preview — the caret's offset is measured against the wrong node.";

describe('shouldDropComment', () => {
  it('drops an AI triage brief', () => {
    expect(shouldDropComment(AGENT_BRIEF_946)).toBe(true);
  });

  it('drops a triage-marked supersede note', () => {
    expect(shouldDropComment(SUPERSEDED_906)).toBe(true);
  });

  it('matches the marker whatever case the agent writes it in', () => {
    expect(shouldDropComment('> *THIS WAS GENERATED BY AI DURING TRIAGE.*\n\nanything')).toBe(true);
    expect(shouldDropComment('generated by AI during triage')).toBe(true);
  });

  it('drops an empty or whitespace-only comment', () => {
    expect(shouldDropComment('')).toBe(true);
    expect(shouldDropComment('   \n  ')).toBe(true);
    expect(shouldDropComment(null)).toBe(true);
    expect(shouldDropComment(undefined)).toBe(true);
  });

  it('keeps a human comment for laundering rather than dropping it', () => {
    // This one is unsafe to relay raw — it names two issue numbers a submitter
    // cannot open — but the marker cannot see that. Laundering is what handles
    // it, which is why the predicate must not be the only line of defence.
    expect(shouldDropComment(HUMAN_SHORTHAND_906)).toBe(false);
  });

  it('keeps an ordinary answer', () => {
    expect(shouldDropComment('Good catch — this is on the roster screen, top right.')).toBe(false);
  });
});

describe('the relay prompts', () => {
  it('forbid issue references in both directions, since a submitter cannot open one', () => {
    for (const instruction of [LAUNDER_INSTRUCTION, CLOSE_SUMMARY_INSTRUCTION]) {
      expect(instruction).toMatch(/#123/);
      expect(instruction.toLowerCase()).toContain('never mention github');
    }
  });

  it('forbid code, paths and error text reaching a submitter', () => {
    for (const instruction of [LAUNDER_INSTRUCTION, CLOSE_SUMMARY_INSTRUCTION]) {
      expect(instruction.toLowerCase()).toContain('never include code');
    }
  });

  it('each carry the escape hatch that lets the model decline', () => {
    expect(LAUNDER_INSTRUCTION).toContain('"relay" to false');
    expect(CLOSE_SUMMARY_INSTRUCTION).toContain('"usable" to false');
  });

  it('keeps the marker lowercase, because the check lowercases its input', () => {
    expect(TRIAGE_COMMENT_MARKER).toBe(TRIAGE_COMMENT_MARKER.toLowerCase());
  });
});
